"""initial schema (autogenerated from models on first upgrade)

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-14 00:00:00

This migration uses ``create_all`` on the metadata bound to the app's
SQLAlchemy registry. It is the single source of truth for the initial
schema. Subsequent migrations are autogenerated by Alembic in the
usual way (``flask db revision --autogenerate``).
"""
from alembic import op
from sqlalchemy import inspect

from app.extensions import db
from app import models  # noqa: F401 — ensure models import for metadata


revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    db.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    # Drop in reverse dependency order
    insp = inspect(bind)
    for table in reversed(db.metadata.sorted_tables):
        if insp.has_table(table.name):
            table.drop(bind=bind, checkfirst=True)
